"""Add Jira SourceApp and Update PKs

Revision ID: efb81c4544aa
Revises: 
Create Date: 2026-04-01 10:43:34.123278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'efb81c4544aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # --- 1. GAudit ---
    op.add_column('GAudit', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.alter_column('GAudit', 'UserID', existing_type=sa.INTEGER(), type_=sa.String(length=100), existing_nullable=True)

    # --- 2. GComments ---
    op.add_column('GComments', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.alter_column('GComments', 'UserID', existing_type=sa.INTEGER(), type_=sa.String(length=100), existing_nullable=False)

    # --- 3. GComponents ---
    op.drop_constraint('PK_GComponents', 'GComponents', type_='primary')
    op.add_column('GComponents', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.create_primary_key('PK_GComponents', 'GComponents', ['ComponentID', 'SourceApp'])

    # --- 4. GIssueCustomFields ---
    # Προσοχή στο όνομα του υπάρχοντος PK. Συνήθως είναι PK_GIssueCustomFields.
    op.drop_constraint('PK__GIssueCu__38852449D809869E', 'GIssueCustomFields', type_='primary')
    op.add_column('GIssueCustomFields', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.create_primary_key('PK_GIssueCustomFields', 'GIssueCustomFields', ['IssueID', 'CustomFieldID', 'SourceApp'])

    # --- 5. GIssues ---
    op.drop_constraint('PK_GIssues', 'GIssues', type_='primary')
    op.add_column('GIssues', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.add_column('GIssues', sa.Column('IssueKey', sa.String(length=50), nullable=True))
    op.create_primary_key('PK_GIssues', 'GIssues', ['IssueID', 'SourceApp'])
    
    # Μερικά χρήσιμα string size alters που βρήκε το Alembic για τα issues
    op.alter_column('GIssues', 'Reporter', existing_type=sa.NVARCHAR(length=100), type_=sa.String(length=255), nullable=True)

    # --- 6. GProjects ---
    op.drop_constraint('PK_GProjects', 'GProjects', type_='primary')
    op.add_column('GProjects', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.create_primary_key('PK_GProjects', 'GProjects', ['ProjectID', 'SourceApp'])

    # --- 7. GTimeTracking ---
    op.drop_constraint('PK_GTimeTracking', 'GTimeTracking', type_='primary')
    op.add_column('GTimeTracking', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.create_primary_key('PK_GTimeTracking', 'GTimeTracking', ['TimeEntryID', 'SourceApp'])

    # --- 8. GUsers ---
    op.drop_constraint('PK_GUsers', 'GUsers', type_='primary')
    # ΠΡΩΤΑ αλλάζουμε τον τύπο σε String και ΜΕΤΑ φτιάχνουμε το νέο PK
    op.alter_column('GUsers', 'UserID', existing_type=sa.INTEGER(), type_=sa.String(length=100), existing_nullable=False)
    op.add_column('GUsers', sa.Column('SourceApp', sa.String(length=50), server_default='Gemini', nullable=False))
    op.create_primary_key('PK_GUsers', 'GUsers', ['UserID', 'SourceApp'])
    
    op.alter_column('GUsers', 'Username', existing_type=sa.NVARCHAR(length=255), type_=sa.String(length=150), nullable=True)
    op.alter_column('GUsers', 'Fullname', existing_type=sa.NVARCHAR(length=255), type_=sa.String(length=300), nullable=True)
    op.alter_column('GUsers', 'APIKey', existing_type=sa.NVARCHAR(length=12), type_=sa.String(length=255), nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SyncMetadata', 'LastSyncAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('SyncMetadata', 'EntityName',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               existing_nullable=False)
    op.alter_column('SyncLogDetails', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('SyncLogDetails', 'OccuredAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('SyncLogDetails', 'LogType',
               existing_type=sa.Enum('Info', 'Error', 'Summary', 'Detail', name='synclogtypeenum'),
               type_=sa.NVARCHAR(length=10, collation='Greek_CI_AS'),
               nullable=True)
    op.alter_column('SyncLogDetails', 'RecordID',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=True)
    op.alter_column('SyncLog', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('SyncLog', 'LogFilePath',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=500, collation='Greek_CI_AS'),
               existing_nullable=True)
    op.alter_column('SyncLog', 'Status',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               existing_nullable=True)
    op.alter_column('SyncLog', 'FinishedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('SyncLog', 'StartedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('SyncLog', 'EntityName',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               existing_nullable=False)
    op.alter_column('GUsers', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('GUsers', 'CreationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('GUsers', 'APIKey',
               existing_type=sa.String(length=255),
               type_=sa.NVARCHAR(length=12, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GUsers', 'Email',
               existing_type=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GUsers', 'Fullname',
               existing_type=sa.String(length=300),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GUsers', 'Surname',
               existing_type=sa.String(length=150),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               existing_nullable=True)
    op.alter_column('GUsers', 'Firstname',
               existing_type=sa.String(length=150),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GUsers', 'Username',
               existing_type=sa.String(length=150),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GUsers', 'UserID',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('GUsers', 'SourceApp')
    op.add_column('GTimeTracking', sa.Column('RowVersion', mssql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('GTimeTracking', 'IssueComponent',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               existing_nullable=True)
    op.alter_column('GTimeTracking', 'TimeTypeID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('GTimeTracking', 'TimeCreationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('GTimeTracking', 'TimeEntryDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.drop_column('GTimeTracking', 'SourceApp')
    op.alter_column('GProjects', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('GProjects', 'CreationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('GProjects', 'ProjectName',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=255, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GProjects', 'ProjectCode',
               existing_type=sa.String(),
               type_=sa.NVARCHAR(length=6, collation='Greek_CI_AS'),
               nullable=False)
    op.drop_column('GProjects', 'SourceApp')
    op.alter_column('GIssues', 'ImportedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               nullable=False)
    op.alter_column('GIssues', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('GIssues', 'ClosedDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('GIssues', 'RevisedDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('GIssues', 'CreationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('GIssues', 'Status',
               existing_type=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GIssues', 'Resolution',
               existing_type=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GIssues', 'Severity',
               existing_type=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GIssues', 'Priority',
               existing_type=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GIssues', 'Type',
               existing_type=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.alter_column('GIssues', 'Reporter',
               existing_type=sa.String(length=255),
               type_=sa.NVARCHAR(length=100, collation='Greek_CI_AS'),
               nullable=False)
    op.drop_column('GIssues', 'IssueKey')
    op.drop_column('GIssues', 'SourceApp')
    op.drop_column('GIssueCustomFields', 'SourceApp')
    op.alter_column('GComponents', 'RowVersion',
               existing_type=sa.LargeBinary(),
               type_=mssql.TIMESTAMP(),
               nullable=False)
    op.alter_column('GComponents', 'CreationDate',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.drop_column('GComponents', 'SourceApp')
    op.create_index(op.f('IX_GComments_IssueID'), 'GComments', ['IssueID'], unique=False)
    op.alter_column('GComments', 'UserID',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('GComments', 'SourceApp')
    op.create_index(op.f('IX_GAudit_IssueID'), 'GAudit', ['IssueID'], unique=False)
    op.alter_column('GAudit', 'UserID',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('GAudit', 'SourceApp')
    # ### end Alembic commands ###
