# Στοιχεία Πρόσβασης Jira
JIRA_EMAIL = "d.batsilis@epsilon-singularlogic.eu"
JIRA_TOKEN = "ATATT3xFfGF0J6OGMZEVMxniIDNv0zk9QuNoufR7s2CkcxgI9zMuJyzt8qdWmqBAi48OaV1B_7-70Ui9owiVYHrTta49vhxinZ8X4goqOBIvU0bOrs5_KFtewTPpBTaaHrQhjEA9pme7NluinJzuF8TGDxihTD0E1EZul5m3NbgvOKYlMzkXsOQ=67ACB5D1"

# Μπορείτε να προσθέσετε και άλλα στοιχεία μελλοντικά
PROJECT_NAME = "NSS Support Dashboard"